### ISSUE TITLE
Sign in error

### ISSUE THREAD

**Issue by matdeofloggi** [jupyterlab/jupyterlab-google-drive#134]
After selecting an account to sign in, i'm getting the following error message

![image](https://user-images.githubusercontent.com/25035932/41127898-b542c9ee-6a82-11e8-997c-99124deeb652.png)

I couldn't find any fix so far

Thanks

**Comment by ian-r-rose** [comment]
Hi @matdeof, thanks for the report.

I think that a week or two ago Google has started increasing the verification requirements for third-pary Google Drive integrations (such as this one).  Unfortunately, I think that means that the default `CLIENT_ID` used by this extension will no longer work. Ultimately, it is probably the correct decision from a security standpoint, since Google *cannot* verify that the default `CLIENT_ID` is who it says it is (i.e., JupyterLab developers). But it does make distributing this extension more difficult.

We will have to respond to this development, but in the mean time you should still be able to create your own credentials using the instructions [here](https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/docs/advanced.md). It is kind of an involved process, but should work.

If you run into any troubles, or have feedback on how to make the instructions clearer, feel free to ask them here!

**Comment by matdeof** [comment]
Hi @ian-r-rose, 

I'll follow the instructions and i reach you guys in case i have any troubles.

 Thanks a lot, for the quick reply and for all the infomation as well!

**Comment by matdeof** [comment]
So quick update, gladly i manage to follow your tutorial and now i'm able to sign in Google Drive, great tutorial! Thanks again! @ian-r-rose

**Comment by ian-r-rose** [comment]
Glad to hear it! I'll leave this open until I can update the documentation to communicate the changes to Google's verification process.

**Comment by alex-choquette** [comment]
Hi @ian-r-rose,

I had the same issue with signing in, and following the [tutorial](https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/docs/advanced.md) solved it for me.
I can now access my Google Drive though JupyterLab and it seems to sync in real-time with my account !

My issue: when I try to open a file, let say a notebook, from Google Drive (in JupyterLab), it loads to infinity and never opens. The same thing happens when trying to create a new notebook.

What should I do?
Thanks.

**Comment by ian-r-rose** [comment]
Hi @alex-choquette are there any errors output to the Javascript console (usually opened with F12)?

**Comment by ian-r-rose** [comment]
Also, have you set realtime to false as described [here](https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/docs/advanced.md#realtime-api)?

**Comment by alex-choquette** [comment]
Actually yes, I get this error.
<img width="830" alt="capture d ecran 2018-07-20 a 16 15 08" src="https://user-images.githubusercontent.com/41489338/43023358-926504f0-8c38-11e8-9f23-e0491e2b00d5.png">

And yes, I have put the realtime settings to false as such
<img width="1679" alt="capture d ecran 2018-07-20 a 16 13 56" src="https://user-images.githubusercontent.com/41489338/43023359-927ff166-8c38-11e8-96e8-9ec5c770030b.png">

**Comment by alex-choquette** [comment]
Actually yes, I get this error
<img width="1679" alt="capture d ecran 2018-07-20 a 16 13 56" src="https://user-images.githubusercontent.com/41489338/43023410-c4a592e0-8c38-11e8-83f8-e4b47c09cc9d.png">

And I have set the realtime setting to false as such
<img width="830" alt="capture d ecran 2018-07-20 a 16 15 08" src="https://user-images.githubusercontent.com/41489338/43023423-d27ab9c2-8c38-11e8-9268-6b8060ee88f3.png">

**Comment by alex-choquette** [comment]
It worked! Once again my poor knowledge was the real issue :S 
Let say I want to do realtime editing of a notebook with a collaborator, do I simply need to turn the "realtime" setting to "true" and share the notebook with my partner ?

**Comment by ian-r-rose** [comment]
Glad to hear you got it working! Unfortunately, Google has deprecated their realtime API, and it is no longer allowing new sign-ups (hence the somewhat awkward install process that you discovered).

We are working on a replacement, but it is not ready yet. So for now, you can access your Google Drive account, but it won't have realtime updates.

**Comment by alex-choquette** [comment]
I understand. Thank you for taking the time to answer :) Do you have an idea of approximately when it will be ready? And how can we be notified about it?
Thanks.

**Comment by ian-r-rose** [comment]
I don't know exactly when it will be ready, but rest assured we'll be advertising it :)

**Comment by nabriis** [comment]
The link to the guide is not working anymore.

**Comment by ian-r-rose** [comment]
@nabriis See [here](https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/docs/setup.md)

**Comment by nabriis** [comment]
Actually that is the guide I followed. Maybe I missed something?

**Comment by ian-r-rose** [comment]
What is the link that is broken?

**Comment by nabriis** [comment]
It is this one:
https://github.com/jupyterlab/jupyterlab-google-drive/blob/master/docs/advanced.md
Which is mentioned a bunch of times earlier in the chat. 

I'll give the guide you linked another try.

**Comment by ian-r-rose** [comment]
It's the same file, just renamed.

**Comment by ian-r-rose** [comment]
Closing as answered.
