### ISSUE TITLE
Can't sing in in my drive

### ISSUE THREAD

**Issue by metya** [jupyterlab/jupyterlab-google-drive#151]
So I setup all things properly but can't sing in in my drive tab.

![image](https://user-images.githubusercontent.com/968934/53097729-3593e580-3533-11e9-9bef-37877b1217a2.png)

After I click button sing in, and after click on my google account in popup google login page nothing happens and the tab the same with sing in button and google drive icon on top of that like on the screenshot.

It seems to my credentials is ok, cause earlier everything is just worked but suddenly broke.

**Comment by ian-r-rose** [comment]
@metya Sorry to hear you are having trouble. Was there any upgrade that happened that could have caused things to break? What versions of `jupyterlab` and `@jupyterlab/google-drive` are you using? Do any errors show up on the browser Javascript console?

**Comment by bshouse** [comment]
@metya Upgrading Jupyter Lab to 1.1.4 resolves this issue.

**Comment by metya** [comment]
ok! 

this became even worse))

![image](https://user-images.githubusercontent.com/968934/65267292-6239cb00-db1d-11e9-87f5-e08aa3f00d50.png)

distr - Linux metya 5.2.11-1-MANJARO #1 SMP PREEMPT Thu Aug 29 07:41:24 UTC 2019 x86_64 GNU/Linux

**Comment by bshouse** [comment]
@metya Just to be clear, did it ever work for you?  It sounds like it did, but then failed.

Things to check:
1. In the OAuth consent screen; does Scopes for Google API include`../auth/drive`? 
2. In the OAuth consent screen; Does the Authorized Domains section include localhost (or a similar reference: 127.0.0.1.xip.io)?
3. In the Credentials section; Are the Credentials Type: Web Application? 
4. In the Credentials section; Do you have an Authorized Javascript origin for localhost (or a similar reference: 127.0.0.1.xip.io)?

I suspect that the root cause of the problem is using localhost. You can try to use xip.io or a real domain/ip of which Google is more supportive.

**Comment by metya** [comment]
My excuse! 

On my new distro I forgot to set up the right credentials in settings.
So now it works! 

Thank you!

**Comment by bshouse** [comment]
@metya I am glad to hear you got it working!  When you have a moment, will you please close the issue?  Thank you.

**Comment by metya** [comment]
Of course! 
Thank you for your work!
