### ISSUE TITLE
get 403 error when trying to open google drive file in jupyterlab

### ISSUE THREAD

**Issue by tamama** [jupyterlab/jupyterlab-google-drive#152]
Hi there,

When trying to open a google drive file in Jupyterlab, I get a 403 error.

The following Youtube video explains the fault:
https://www.youtube.com/watch?v=50OEzxIFl4Y

My suspicion is that we may need additional API scopes, such as:
https://www.googleapis.com/auth/drive
https://www.googleapis.com/auth/drive.metadata

May I know how could I fix it?

Kind regards,
Tamama

**Comment by ian-r-rose** [comment]
Hi @tamama, it looks like you have the "realtime" option enabled in the settings. Because Google has turned off realtime support for third-party apps, we now need to disable that here.

Can you follow the instructions [here](https://github.com/jupyterlab/jupyterlab-google-drive/blob/v0.14.0/docs/setup.md#realtime-api) to see if that fixes your problem?

**Comment by tamama** [comment]
Awesome! This fixes my problem.

Thanks!
