### ISSUE TITLE
[Feature request] Support exporting to

### ISSUE THREAD

**Issue by ktong** [jupyterlab/jupyterlab-google-drive#51]
It shows 404 when exporting notebook on gDrive to HTML/PDF.

404 : Not Found
You are requesting a page that does not exist!

**Comment by ian-r-rose** [comment]
Thanks, @ktong, this would indeed be useful. It is somewhat tricky, as the `nbconvert` API takes a path to the notebook, which assumes it is on the notebook server filesystem, rather than stored somewhere else (such as Google Drive). I just spoke to @mpacer about this, and it would likely require an additional endpoint to the API that sends the notebook JSON to `nbconvert` (which we have wanted for other reasons as well).

**Comment by ktong** [comment]
Thanks, @ian-r-rose. Looking forward that. By the way, passing notebook to nbconvert also benefits my another project.

**Comment by mpacer** [comment]
@ktong what's the other project?

**Comment by ktong** [comment]
It's an internal project uses nbconvert to generate reports base on parameters passed

**Comment by mirestrepo** [comment]
Hi, are there any ongoing efforts to implement this feature? We are also very interested. Thanks!

**Comment by mirestrepo** [comment]
@ian-r-rose Is this something that you plan incorporating in the "near" future? Thanks!

**Comment by ian-r-rose** [comment]
Unfortunately, I believe this is still blocked by the `nbconvert` API. It expects a path to the notebook on the file system of the notebook server, which is quite different from the Google Drive model. I think the way to move forwards on this is to (re)open the discussion on the notebook nbconvert API to try to allow POSTing of notebook contents.

Alternatively, we could consider writing our own nbconvert serverextension that does this and hitting that endpoint with this extension. I would be happy to provide guidance/help on that effort.

**Comment by mirestrepo** [comment]
nbconvert can be used as a library inside a python script, where I think it accepts JSON https://nbconvert.readthedocs.io/en/latest/nbconvert_library.html
Is that of any help? Or is it the case that because the extesions are javascript we can only use the command-line version of nbconvert? Sorry if I'm being a little naive in how this all works....

**Comment by mirestrepo** [comment]
I think I understand... And I may be interested into looking more into this in the future

For now... I'm working within JupyterHub and I don't want students to install nbcovert locally... As a hack (for the short term) I'm thinking I could write a python script that gets the notebook file from google drive using the its url...then using nbconvert inside the notebook... would that make any sense? Downloading the notebook works, so I'm assuming this could be a possible path.... However I am unsure how to get the url/notebook programmatically within python and perhaps reusing the authentication that is granted to the extension. Do you have any guidance on doing so?

**Comment by ian-r-rose** [comment]
I am having a hard time thinking of a way of doing this that doesn't involve at least a *bit* of Javascript :smile:. In particular, getting the path to a notebook is done on the browser side. Do you envision the resulting converted notebook to be produced on the server, or re-uploaded to Google Drive?
